module.exports = {
  content: ['./src/**/*.{html,js}', './index.html'],
  theme: {
    extend: {
      screens: {
        'max-md': { max: '768px' },
      },
      fontFamily: {
        nanum: ['NanumSquareRound', 'sans-serif'],
        baskin: ['BaskinRobbins', 'sans-serif'],
      },
      backgroundImage: (theme) => ({
        "header-bg": "url('../images/png/common/bg_header.png')",
        "icon-nav-search": "url('../images/webp/common/icon_nav_search.webp')",
        "icon-search": "url('../images/webp/common/icon_search.webp')",
        "icon-facebook": "url('../images/png/common/sns_facebook_35.png')",
        "icon-twitter": "url('../images/png/common/sns_twitter_35.png')",
        "icon-instagram": "url('../images/png/common/sns_instagram_35.png')",
        "icon-blog": "url('../images/png/common/sns_blog_35.png')",
        "icon-youtube": "url('../images/png/common/sns_youtube_35.png')",
        "icon-customer-center": "url('../images/webp/common/icon_customer_center 1.webp')",
        "btn-happypoint": "url('../images/webp/common/btn_happypoint.webp')",
        "btn-happymarket": "url('../images/webp/common/btn_happymarket.webp')",
        "btn-spc": "url('../images/webp/common/btn_spc_story.webp')",
        "btn-norton": "url('../images/png/common/btn_norton.png')",
        "btn-ccm": "url('../images/webp/common/btn_ccm_2.webp')",
        "btn-ksa": "url('../images/webp/common/btn_ksa.webp')",
        "btn-hamburger": "url('../images/webp/common/button-hamburger.webp')",
        "btn-close": "url('../images/webp/common/btn_close.webp')",
        "footer-logo": "url('../images/webp/common/footer_logo.webp')",
        "select-dropdown": "url('../images/select_dropdown.png')",
      }),
      colors: {
        pink1: '#FF7C98',
        pink2: '#E01883',
        navy1: '#224289',
        beige1: '#F9F8F7',
        brown1: '#918984',
        brown2: '#726454',
        white: '#FEFEFE',
        white1: '#ededed',
        gray: '#CDCCD5',
        gray2: '#7E7E81',
        black1: '#2F231C',
        black2: '#321C15',
      },
    },
  },
  plugins: [],
};
